### Create

POST http://localhost:3030/library
Content-Type: application/json

{
    "book_name": "junkes" ,
    "author_name": "autor teste",
    "number_pages": 36,
    "copies_available": 50
}

### FindAll

GET http://localhost:3030/library


### FindOne
GET http://localhost:3030/library/3


### Update
PUT http://localhost:3030/library/2
Content-Type: application/json

{
    "book_name": "livro teste" ,
    "author_name": "autor teste",
    "number_pages": 36,
    "copies_available": 50
}

### Delete
DELETE http://localhost:3030/library/2
